fix(ts): ignore import errors for `got-scraping`
This resolves a TS build issue:

```
node_modules/@crawlee/http/internals/http-crawler.d.ts:9:49 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("got-scraping")' call instead.

9 import type { OptionsInit, PlainResponse } from 'got-scraping';
                                                  ~~~~~~~~~~~~~~
```